### ISSUE TITLE
Masking layer_repeat_vector in LSTM autoencoder

### ISSUE THREAD

**Issue by AleBitetto** [rstudio/keras#1191] opened 2021-02-23 21:46 UTC
I am building an LSTM autoencoder in R keras with different timestep inputs. As ragged tensors are not implemented yet I opted for masking shorter length inputs. The problem I'm facing is in the bottleneck layer where the layer_repeat_vector destroys the masking.

I found this helpful solution https://stackoverflow.com/a/59313862/4601329, and I'm trying to translate the Second Solution of the answer.

Here's my code:
```
library(keras)

# custom lstm bottleneck layer to keep masking after layer_repeat_vector
lstm_with_mask <- R6::R6Class("lstm_with_mask",
                              
                              inherit = KerasLayer,
                              
                              public = list(
                                
                                lstm_units = NULL,
                                in_shp = NULL,    # c(timesteps, features)
                                activation = NULL,
                                
                                initialize = function(lstm_units = NULL,
                                                      in_shp = NULL,
                                                      activation = NULL) {
                                  
                                  
                                  self$lstm_units <- lstm_units
                                  self$in_shp <- in_shp
                                  self$activation <- activation
                                  # self$lstm_layer <- layer_lstm(units = lstm_units, input_shape = in_shp, activation = activation, return_sequences = FALSE)
                                  # self$repeat_layer <- layer_repeat_vector(n=in_shp[1])   # timestep
                                },
                                
                                compute_mask = function(input, input_mask=NULL) {
                                  return(input_mask)
                                },
                                
                                call = function(x, mask = NULL) {
                                  
                                  l1 <- layer_lstm(units = self$lstm_units, input_shape = self$in_shp, activation = self$activation, return_sequences = FALSE)
                                  l2 <- layer_repeat_vector(n=self$in_shp[1])   # timestep

                                  return(l2(l1(x)))
                                  # return(self$repeat_layer(self$lstm_layer(x)))
                                }
                              )
)

# define layer wrapper function
layer_lstm_with_mask <- function(object, lstm_units = NULL,
                                 in_shp = NULL,    # c(timesteps, features)
                                 activation = NULL,
                                 name = 'lstm_with_mask') {
  create_layer(lstm_with_mask, object, list(lstm_units =  lstm_units, 
                                            in_shp = in_shp, 
                                            activation = activation,
                                            name = name
  ))
}


model <- keras_model_sequential()
model %>%
  layer_masking(mask_value = -9999,input_shape = c(timesteps_var, features)) %>%
  layer_lstm(units = 100, input_shape = c(timesteps_var, features), activation='relu', return_sequences = TRUE) %>%
  layer_lstm_with_mask(lstm_units = 50, in_shp = c(timesteps_var, features), activation='relu')
```
but if I check the masking with
```
for (ll in model$layers){
  cat('\n-----')
  print(ll$name)
  print(ll$input_mask)
  print(ll$output_mask)
}
```
I get
```
-----[1] "masking_18"
NULL
Tensor("masking_18/Identity_1:0", shape=(None, 6), dtype=bool)

-----[1] "lstm_64"
Tensor("masking_18/Identity_1:0", shape=(None, 6), dtype=bool)
Tensor("masking_18/Identity_1:0", shape=(None, 6), dtype=bool)

-----[1] "lstm_with_mask"
Tensor("masking_18/Identity_1:0", shape=(None, 6), dtype=bool)
NULL
```
so the masking is still lost.

I think the problem is in defining the LSTM and RepeatVector inside `call` so that the edited `compute_mask` (explicitly returning the mask) doesn't affect the results. The proper way should be initializing both in the `initialize` function, but if I use the commented commands I get the following error
`Error in self$lstm_layer <- layer_lstm(units = lstm_units, input_shape = in_shp, : cannot add bindings to a locked environment`
Any suggestion? Thanks a lot

**Comment by dfalbel** [comment] 2021-02-24 13:33
Hi @AleBitetto 

The problem is that `compute_mask` is never called because it's not wrapped by the R custom layer.
You can do something like this using the new `Layer` function that allows for more general custom layers:

``` r
library(keras)

# custom lstm bottleneck layer to keep masking after layer_repeat_vector
lstm_with_mask <- Layer(
  "lstm_with_mask",
  
  initialize = function(lstm_units = NULL,
                        in_shp = NULL,
                        activation = NULL) {
    
    super()$`__init__`()
    self$lstm_units <- lstm_units
    self$in_shp <- in_shp
    self$activation <- activation
    self$lstm_layer <- layer_lstm(units = lstm_units, input_shape = in_shp, 
                                  activation = activation, 
                                  return_sequences = FALSE
    )
    self$repeat_layer <- layer_repeat_vector(n=in_shp[1])   # timestep
  },
  
  compute_mask = function(input, mask=NULL) {
    return(mask)
  },
    
  call = function(x, training = FALSE, mask = NULL) {
    
    #l1 <- layer_lstm(units = self$lstm_units, input_shape = self$in_shp, activation = self$activation, return_sequences = FALSE)
    #l2 <- layer_repeat_vector(n=self$in_shp[1])   # timestep
    
    #return(l2(l1(x)))
    return(self$repeat_layer(self$lstm_layer(x)))
  }
)

timesteps_var <- 10
features <- 5
model <- keras_model_sequential()
model %>%
  layer_masking(mask_value = -9999,input_shape = c(timesteps_var, features)) %>%
  layer_lstm(units = 100, input_shape = c(timesteps_var, features), activation='relu', return_sequences = TRUE) %>%
  lstm_with_mask(lstm_units = 50, in_shp = c(timesteps_var, features), activation='relu')


for (ll in model$layers){
  cat('\n-----')
  print(ll$name)
  print(ll$input_mask)
  print(ll$output_mask)
}
#> 
#> -----[1] "masking"
#> NULL
#> KerasTensor(type_spec=TensorSpec(shape=(None, 10), dtype=tf.bool, name=None), name='masking/Squeeze:0')
#> 
#> -----[1] "lstm_1"
#> KerasTensor(type_spec=TensorSpec(shape=(None, 10), dtype=tf.bool, name=None), name='masking/Squeeze:0')
#> KerasTensor(type_spec=TensorSpec(shape=(None, 10), dtype=tf.bool, name=None), name='Placeholder_2:0')
#> 
#> -----[1] "lstm_with_mask"
#> KerasTensor(type_spec=TensorSpec(shape=(None, 10), dtype=tf.bool, name=None), name='Placeholder_2:0')
#> KerasTensor(type_spec=TensorSpec(shape=(None, 10), dtype=tf.bool, name=None), name='Placeholder_2:0')
```

<sup>Created on 2021-02-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by AleBitetto** [comment] 2021-02-24 16:36
@dfalbel Thansk for the reply. Now it seems I cannot use the `Layer` function.

> could not find function "Layer"

this is my session info
```
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Italian_Italy.1252  LC_CTYPE=Italian_Italy.1252    LC_MONETARY=Italian_Italy.1252 LC_NUMERIC=C                   LC_TIME=Italian_Italy.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tensorflow_2.2.0 keras_2.3.0.0    reticulate_1.18 

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6      lattice_0.20-38   fansi_0.4.1       withr_2.1.2       crayon_1.3.4      assertthat_0.2.1  zeallot_0.1.0     rappdirs_0.3.3    grid_3.6.3       
[10] R6_2.5.0          jsonlite_1.6.1    magrittr_2.0.1    cli_2.0.2         tfruns_1.4        rstudioapi_0.11   whisker_0.3-2     Matrix_1.2-18     generics_0.1.0   
[19] tools_3.6.3       glue_1.4.0        yaml_2.2.1        compiler_3.6.3    base64enc_0.1-3   sessioninfo_1.1.1
```

**Comment by AleBitetto** [comment] 2021-02-24 16:46
@dfalbel thanks for the reply. Now I cannot find the `Layer` function getting

> Error in Layer("lstm_with_mask", initialize = function(lstm_units = NULL,  : 
>   could not find function "Layer"

my session is
```
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Italian_Italy.1252  LC_CTYPE=Italian_Italy.1252    LC_MONETARY=Italian_Italy.1252 LC_NUMERIC=C                   LC_TIME=Italian_Italy.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tensorflow_2.2.0 keras_2.3.0.0   

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6    lattice_0.20-38 zeallot_0.1.0   rappdirs_0.3.3  grid_3.6.3      R6_2.5.0        jsonlite_1.6.1  magrittr_2.0.1  tfruns_1.4      whisker_0.3-2  
[11] Matrix_1.2-18   reticulate_1.18 generics_0.1.0  tools_3.6.3     yaml_2.2.1      compiler_3.6.3  base64enc_0.1-3
```

**Comment by dfalbel** [comment] 2021-02-24 16:59
Oh, sorry, it's not yet on CRAN. You will need the dev version of Keras.
Instal with

```
remotes::install_github("rstudio/keras")
```

**Comment by AleBitetto** [comment] 2021-02-24 22:47
Thanks a lot, it works!

**Comment by dfalbel** [comment] 2021-02-24 23:35
Cool ! Glad it works! I'll close the issue, feel free to open a new one if there's something wrong.

**Closed by dfalbel** 2021-02-24 23:35 UTC
