### ISSUE TITLE
predict_generator() for image classification is freezing and doesn't produce any output

### ISSUE THREAD

**Issue by juliavassey** [rstudio/keras#786] opened 2019-05-23 16:30 UTC
Hello! I'm trying to predict labels on a test set of unlabeled images using predict_generator()

```
predict_generator(model, test_gen, steps = 1)

```

Or this code:

```
preds <- keras::predict_generator(model,
                                    test_gen,
                                    verbose = 1,
                                    steps = 1,
                                    max_queue_size = 1)
                                    #workers=4)
```

When I run either of these codes, R does not spit out any errors and neither gives any output. It just freezes and every time I have to force quit it. 

The model is compiled and trained via transfer learning using Inception V3. My training and validation data set consists of about 1,000 images of 6 categories. The lines of codes for training the model are below:

```
base_model = applications.InceptionV3(weights='imagenet', include_top=False, input_shape=(img_width, img_height, 3))

freeze_weights(base_model)

model_top = base_model$output %>%
layer_global_average_pooling_2d() %>%
layer_dense(units = 128, activation = "relu") %>%
layer_dropout(0.7) %>%
layer_dense(units = 6, activation = "softmax")

model = keras_model(inputs = base_model$input, outputs = model_top)

length(model$layers)

freeze_weights(model, 1, length(model$layers) - 3)
summary(model)

#Compile the model 
model %>%
compile(optimizer =
optimizer_adam(#lr = 0.00001,
#lr = 0.0005,
lr = 0.00001,
epsilon = 1e-08),
loss = "categorical_crossentropy",
metrics = "accuracy")
```
Appreciate if you can give me any hints of why predict_generator() might not work. Or perhaps offer an alternative prediction function. 

Thank you

**Comment by dfalbel** [comment] 2019-05-24 21:49
@juliavassey can you tell how are you building the `test_gen` object, please?

**Comment by juliavassey** [comment] 2019-05-24 22:45
Here are the codes building up to test_gen:

```
dirs$test = paste0(dirs$base, "/test_unlabeled")
dir.exists(dirs$test)

img_width = img_height = 299L


test_datagen = keras::image_data_generator(rescale = 1/255)

test_gen =
  test_datagen$flow_from_directory(dirs$test,
                                    target_size = c(img_width, img_height),                                   
batch_size = 1, class_mode = NULL, shuffle = FALSE)

```

Thank you

**Comment by juliavassey** [comment] 2019-05-24 22:46
In addition: test_unlabeled folder does not have any subdirectory folders, just unlabeled images.

**Comment by dfalbel** [comment] 2019-05-27 12:50
I can't reproduce the error on my side. Here's the code I am running:

```r
dir <- tempdir()
dir.create(paste0(dir, "/flow-img"))
dir <- paste0(dir, "/flow-img")
dir.create(paste0(dir, "/0"))
dir.create(paste0(dir, "/1"))

mnist <- dataset_mnist()
ind <- which(mnist$train$y %in% c(0, 1))

for (i in ind) {
  img <- mnist$train$x[i,,]/255
  rname <- paste(sample(letters, size = 10, replace = TRUE), collapse = "")
  jpeg::writeJPEG(img, target = paste0(dir, "/", mnist$train$y[i], "/", rname, ".jpeg"))
}

img_gen <- image_data_generator()

gen <- flow_images_from_directory(
  directory = dir, 
  generator = img_gen, 
  target_size = c(28, 28), 
  batch_size = 32
)

model <- keras_model_sequential() %>% 
  layer_flatten(input_shape = c(28,28, 3)) %>% 
  layer_dense(units = 2, activation = "softmax")

model %>% compile(loss = "binary_crossentropy", optimizer = "adam")

# test fitting the model
model %>% fit_generator(gen, steps_per_epoch = 20)

# test predictions
preds <- predict_generator(model, gen, steps = 10)

# evaluate
eva <- evaluate_generator(model, gen, steps = 10)
```

Can you try modifying so I get the same error as you have?

**Comment by juliavassey** [comment] 2019-05-28 19:45
I tried to build test_gen using flow_images_from_directory function as in your code and am getting the following error:

```
test_gen =
  test_datagen$flow_images_from_directory(dirs$test,
                                    # Images will be resized to this target size.
                                     target_size = c(img_width, img_height),                                                             batch_size = 1, class_mode = NULL, shuffle = FALSE)
```

Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: 'ImageDataGenerator' object has no attribute 'flow_images_from_directory'

My model (train and val) and test_gen are built on flow_from_directory function, not flow_images_from_directory . 

```
 test_gen =
  test_datagen$flow_from_directory(dirs$test,
                              # Images will be resized to this target size.
                                target_size = c(img_width, img_height),                                                             batch_size = 1, class_mode = NULL, shuffle = FALSE)

When I tried test fitting on my test_gen, the machine is freezing. No error and no results. I have to interrupt the process and force quit R. 

# test fitting the model
```
 new_model %>% fit_generator(test_gen, steps_per_epoch = 20)
```
I do not know if I have to retrain the whole model using flow_images_from_directory to build train and validation objects as well or is it unlikely that this function is causing the issue?

**Comment by dfalbel** [comment] 2019-05-28 20:28
Why do you need to use `$flow_from_directory` and not `flow_images_from_directory`?

**Comment by juliavassey** [comment] 2019-05-28 20:31
The only reason is that my model was trained with $flow_from_directory. Do you think this might be causing the issue? If so, I can try to re-train the model using flow_images_from_directory and update on the progress? Sounds like that's what you are suggesting me to do?

**Comment by juliavassey** [comment] 2019-05-28 20:34
However, maybe it has nothing to do with re-training the model? I am wondering why this code is giving me the error:

```
test_gen =
  test_datagen$flow_images_from_directory(dirs$test,
                                    # Images will be resized to this target size.
                                     target_size = c(img_width, img_height),                                                             batch_size = 1, class_mode = NULL, shuffle = FALSE)

```
Error in py_get_attr_impl(x, name, silent) :
AttributeError: 'ImageDataGenerator' object has no attribute 'flow_images_from_directory'

**Comment by dfalbel** [comment] 2019-05-28 20:38
This error is expected since `test_datagen` does not have a `flow_images_from_directory` method.

I am asking why do you need to use `$flow_from_directory` and not using `keras::flow_images_from_directory()`? 

`keras::flow_images_from_directory()` is just a simple wraper around `$flow_from_directory` but it makes sure all the paths are correct....

**Comment by juliavassey** [comment] 2019-05-28 20:48
Just tried using flow_images_from_directory with this code:

```
test_gen =
  keras::flow_images_from_directory(dirs$test, generator = image_data_generator(),
                                    # Images will be resized to this target size.
                                    target_size = c(img_width, img_height), color_mode = "rgb", batch_size = 1, class_mode = "categorical", shuffle = FALSE)
```
no error this time. But new_model %>% fit_generator(test_gen, steps_per_epoch = 20) still does not give any results. But again, new model's train and val_gen where built with flow_from_directory. 
So next step is retraining the model then with flow_images_from_directory for building train_gen and val_den?

**Comment by eafpres** [comment] 2019-05-28 21:33
FYI, I have been trying to debug this and I am using the standard wrappers.  The following runs, produces no errors, but results in preds being an empty list.  If I, for example, increase the number of steps in the last call, so that it would loop through images more than once, it takes longer but still produces nothing:

` 
  root_path <- "C:/EAF LLC/aa-Analytics and BI/Julia_Vassey"
  setwd(root_path)
#  
  reticulate::use_condaenv("keras-gpu")
  library(keras)
  library(dplyr)
  library(ggplot2)
#
  test_img_dir <-
    paste0(root_path, "/test_unlabeled")
  num_test_imgs <-
    nrow(dir(test_img_dir) %>% 
           as.data.frame(stringsAsFactors = FALSE) %>% 
           rename(file = names(.)[1]) %>% 
           filter(substr(file, nchar(file) - 2, nchar(file)) == "jpg"))
#
# load model
#
  model <- load_model_hdf5("my_model_7.h5")
#
  image_gen_test <- 
    image_data_generator(rescale = 1 / 255, 
                         data_format = "channels_last")  # have tried channels_first, channels_last
  target_x <- 299
  target_y <- 299
  pred_gen_test <- 
    flow_images_from_directory(test_img_dir,
                               generator = image_gen_test,
                               target_size = c(target_x, target_y),
                               color_mode = "rgb",
                               class_mode = "input",  # have tried "categorical" as well
                               batch_size = num_test_imgs,
                               classes = c("e_juice",  # note I have tried w/& w/out classes here
                                           "mod_devices",
                                           "other",
                                           "pod_mod_devices",
                                           "vape_pen",
                                           "warning"),
                               shuffle = FALSE)
  preds <- 
    predict_generator(model,
                      pred_gen_test,
                      steps = 1)  

`

**Comment by dfalbel** [comment] 2019-05-29 00:16
I can't reproduce the error. Could you please try to modify the code I sent above so I can get the same error as you are getting. 

Does running the code above errors for you? Maybe it could be the folder structure or something like this. Without a reproducible example it's too hard to find what the problem is...

**Comment by juliavassey** [comment] 2019-05-29 04:32
Hi Daniel, thank you for your help. Unfortunately, I'm not sure how to re-create the structure part of your code:

```
dir <- tempdir()
dir.create(paste0(dir, "/flow-img"))
dir <- paste0(dir, "/flow-img")
dir.create(paste0(dir, "/0"))
dir.create(paste0(dir, "/1"))

mnist <- dataset_mnist()
ind <- which(mnist$train$y %in% c(0, 1))

for (i in ind) {
  img <- mnist$train$x[i,,]/255
  rname <- paste(sample(letters, size = 10, replace = TRUE), collapse = "")
  jpeg::writeJPEG(img, target = paste0(dir, "/", mnist$train$y[i], "/", rname, ".jpeg"))
}
```

I have 6 classes of images split 80/20 in training and validation sets. Training and validation sets have sub-folders of 6 classes. Test folder has no sub-folders and has unlabeled, un-shuffled  images. All images are .jpg. Feels like the part above is very different?

Here is my folder structure:

```
dirs = list(base = "/Users/juliavassey/Desktop/photos_classifiers")

dirs$train = paste0(dirs$base, "/training")
dirs$val = paste0(dirs$base, "/validation")

img_width = img_height = 299L
batch_size = 5L


#train_datagen = keras::image_data_generator(rescale = 1/255)

#val_datagen = keras::image_data_generator(rescale = 1/255)


img_gen = image_data_generator(rescale = 1 / 255)


train_gen =
  keras::flow_images_from_directory(dirs$train,  generator = img_gen,
                                    # Images will be resized to this target size.
                                    target_size = c(img_width, img_height),
                                    batch_size = batch_size, class_mode = "categorical")

```

and for test is this:

```
dirs$test = paste0(dirs$base, "/test_unlabeled")
dir.exists(dirs$test)


length((test_files = list.files(dirs$test, recursive = TRUE, full.names = TRUE)))


img_width = img_height = 299L
batch_size = 5L

test_datagen = keras::image_data_generator(rescale = 1/255)

test_gen =
  test_datagen$flow_from_directory(dirs$test,
                                    #Images will be resized to this target size.
                                    target_size = c(img_width, img_height), color_mode = "rgb",                                              batch_size = batch_size, class_mode = NULL, shuffle = FALSE)

test_gen =
  test_datagen$flow_from_directory(dirs$test,
                                    # Images will be resized to this target size.
                                    target_size = c(img_width, img_height), color_mode = "rgb", batch_size = batch_size , class_mode = "categorical", shuffle = FALSE)
```

**Comment by juliavassey** [comment] 2019-05-29 18:18
Hi Daniel, I'm actually using transfer learning, not training from scratch. Your code you sent earlier might be for the from scratch training. Do you have any code I can reproduce for Inception_V3 transfer learning? Thank you 

```
base_model = keras::application_inception_v3(include_top = FALSE,
                                             input_shape = c(img_width, img_height, 3L))

model = keras_model(inputs = base_model$input, outputs = model_top)
```

**Comment by dfalbel** [comment] 2019-05-30 16:58
I have added a complete example of fine tuning a pre-trained model here: https://github.com/rstudio/keras/blob/a9297ad6a4bde77a74c6fb4507823980cc4f6779/vignettes/examples/fine_tuning.R

Let me know if it helps. I also just added a fix for `image_data_genrators` that uses `preprocessing_functions`. Let me know if it helps.

**Comment by juliavassey** [comment] 2019-05-30 17:16
Thank you! I will try using Mobile Net. Just to double check, you don't have any examples on training Inception V3 via transfer learning, correct? 

As from what I'm reading online, quoting, the major difference between InceptionV3 and Mobilenet is that Mobilenet uses Depthwise separable convolution while Inception V3 uses standard convolution. This results into lesser number of parameters in MobileNet compared to InceptionV3. However, this results in slight decrease in the performance as well.

**Comment by juliavassey** [comment] 2019-05-30 18:47
Hi Daniel, trying your Mobilenet. While running this chunk below, the error I'm getting is: 
Error: C stack usage  17589015305264 is too close to the limit 


```
model %>% fit_generator(
  generator = training_image_flow, 
  epochs = 5, 
  steps_per_epoch = training_image_flow$n/training_image_flow$batch_size,
  validation_data = validation_image_flow,
  validation_steps = validation_image_flow$n/validation_image_flow$batch_size
)
```
What could be the best and painless way to address this? Thank you

**Comment by dfalbel** [comment] 2019-05-30 19:00
It should work if you install keras from github. I pushed a fix today addressing this. 

```devtools::install_github("rstudio/keras")```

**Comment by juliavassey** [comment] 2019-05-30 19:08
Just tried devtools::install_github("rstudio/keras"). 
getting Error: Could not find tools necessary to compile a package.
What other tools might it need?

Downloading GitHub repo rstudio/keras@master
These packages have more recent versions available.
Which would you like to update?

1:   reticulate (2e48d524d... -> 35da856f6...) [GitHub]

Enter one or more numbers separated by spaces, or an empty line to cancel
1: 1
reticulate (2e48d524d... -> 35da856f6...) [GitHub]
Downloading GitHub repo rstudio/reticulate@master
Error: Could not find tools necessary to compile a package

**Comment by dfalbel** [comment] 2019-05-30 19:36
you can try `devtools::install_github("rstudio/keras", dependencies = FALSE)`

**Comment by juliavassey** [comment] 2019-05-30 20:42
Thank you, Daniel. Have a couple of questions. I ran your example and now it worked, but it returned predictions as an empty file. 

Now I'm modifying the folder structure, too, following your example. 

If I have 6 classes, how should I modify this code? :

```
fs::file_copy(
  path = testing_imgs,
  new_path = gsub("data-raw/PetImages/(Dog|Cat)/", "data/test/images/\\1", testing_imgs)
)
```

In addition, the val_accuracy turned out very low and val_loss super high. So I will try to adjust this for Inception V3 as well.  When I start modifying your code for Inception V3, can I use keras_model function instead of keras_sequence, learning rate,  layer_global_average_pooling_2d()  and lower layer_dense? (as per the lines of code below) 

```
model_top = base_model$output %>%
  layer_global_average_pooling_2d() %>%
  layer_dense(units = 128, activation = "relu") %>%
  layer_dropout(0.7) %>%
  layer_dense(units = 6, activation = "softmax")

model = keras_model(inputs = base_model$input, outputs = model_top)

model %>%
  compile(optimizer =
            optimizer_adam(#lr = 0.00001,
                           #lr = 0.0005,
                           lr = 0.00001,
                           # epsilon is a configuratoin setting for the adam optimizer.
                           epsilon = 1e-08),
          loss = "categorical_crossentropy",
          metrics = "accuracy")
```

Thank you

**Comment by dfalbel** [comment] 2019-05-30 21:01
We need to investigate why you are seeing very low accuracy. I get ~98% after just one epoch. 

Can you tell me what's the result of `tensorflow::tf_config()` ? 

Yes, you can use the functional API, I think you will need to remove the pooling argument from the `application_..` function because it does exactly what `layer_global_average_pooling` will do.

**Comment by juliavassey** [comment] 2019-05-30 21:05
TensorFlow v1.12.0 (~/anaconda2/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow)
Python v3.6 (~/anaconda2/envs/r-tensorflow/bin/python)
after running tensorflow::tf_config()

Also, I'm modifying the folder structure, too, following your example.

If I have 6 classes, how should I modify this code? :

```
fs::file_copy(
  path = testing_imgs,
  new_path = gsub("data-raw/PetImages/(Dog|Cat)/", "data/test/images/\\1", testing_imgs)
)
```

**Comment by juliavassey** [comment] 2019-05-30 21:06
TensorFlow v1.12.0 (~/anaconda2/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow)
Python v3.6 (~/anaconda2/envs/r-tensorflow/bin/python)

**Comment by juliavassey** [comment] 2019-05-30 21:07
And I have TensorFlow v1.12.0, because otherwise keras is not running on 1.13

**Comment by dfalbel** [comment] 2019-05-30 21:34
FYI, I just tested with TensorFlow v1.12.0 and I get 92% accuracy in the middle of the first epoch.

`68/124 [===============>..............] - ETA: 5:12 - loss: 0.1771 - acc: 0.921`

Don't know what could be affecting the results...

I don't know how are your images organised... in order to use `flow_images_from_directory` you need to have a folder per class. In our example the classes are `Cat` and `Dog` so I have those 2 folders. All images of cats are inside `Cats`  and all images of dogs are inside `Dogs`. 

`fs` is great package to manage files from R, but you could do this manually too.

**Comment by juliavassey** [comment] 2019-05-30 21:44
yes, that's exactly what I have and I look at the folder structure in cat's zip. It could be that I have fewer images (you have about 600/300 training and validation per each class and i have about 200/42 per each class). In addition 6 classes might be harder. Could we look at two more errors though. 

```
> fs::file_copy(
   path = training_imgs, 
   new_path = gsub("/Users/juliavassey/Desktop/photos_classifiers_test/",  "data/train",  training_imgs)
 )
```

Error: [ENOENT] Failed to copy '/Users/juliavassey/Desktop/photos_classifiers_test/vape/other/pic_460.jpg' to 'data/trainvape/other/pic_460.jpg': no such file or directory

**Comment by juliavassey** [comment] 2019-05-30 21:45
And also how to modify this for 6 classes?

fs::file_copy(
 path = testing_imgs,
 new_path = gsub("data-raw/PetImages/(Dog|Cat)/", "data/test/images/\\1", testing_imgs)
)

**Comment by juliavassey** [comment] 2019-05-30 22:06
all_imgs <- fs::dir_ls(
  "/Users/juliavassey/Desktop/photos_classifiers_test/", 
  recursive = TRUE, 
  type = "file",
  glob = "*.jpg"
)

# some images are corrupt and we exclude them
# this will make sure all images can be read.
for (im in all_imgs) {
  out <- try(magick::image_read(im), silent = TRUE)
  if (inherits(out, "try-error")) {
    fs::file_delete(im)
    message("removed image: ", im)
  }
}

# re-list all imgs
all_imgs <- fs::dir_ls(
  "/Users/juliavassey/Desktop/photos_classifiers_test/", 
  recursive = TRUE, 
  type = "file",
  glob = "*.jpg"
)

set.seed(6)

training_imgs <- sample(all_imgs, size = length(all_imgs)/2)
validation_imgs <- sample(all_imgs[!all_imgs %in% training_imgs], size = length(all_imgs)/4)       
testing_imgs <- all_imgs[!all_imgs %in% c(training_imgs, validation_imgs)]

# create directory structure
fs::dir_create(c(
  "/Users/juliavassey/Desktop/photos_classifiers_test/data/train/cats",
  "/Users/juliavassey/Desktop/photos_classifiers_test/data/train/dogs",
  "/Users/juliavassey/Desktop/photos_classifiers_test/data/train/parrots",
  "/Users/juliavassey/Desktop/photos_classifiers_test/data/train/mice",
  "/Users/juliavassey/Desktop/photos_classifiers_test/data/train/chickens",
  "/Users/juliavassey/Desktop/photos_classifiers_test/data/train/horses",
  "/Users/juliavassey/Desktop/photos_classifiers_test/data/validation/cats",
  "/Users/juliavassey/Desktop/photos_classifiers_test/data/validation/dogs",
  "/Users/juliavassey/Desktop/photos_classifiers_test/data/validation/parrots",
  "/Users/juliavassey/Desktop/photos_classifiers_test/data/validation/mice",
  "/Users/juliavassey/Desktop/photos_classifiers_test/data/validation/chickens",
  "/Users/juliavassey/Desktop/photos_classifiers_test/data/validation/horses",
  "/Users/juliavassey/Desktop/photos_classifiers_test/data/test/images"
))

all codes below give an error
```
# copy training images
fs::file_copy(
  path = training_imgs, 
  new_path = gsub("/Users/juliavassey/Desktop/photos_classifiers_test", "/Users/juliavassey/Desktop/photos_classifiers_test/data/train", training_imgs)
)

# copy valid images
fs::file_copy(
  path = validation_imgs, 
  new_path = gsub("/Users/juliavassey/Desktop/photos_classifiers_test/", "data/validation", validation_imgs)
)
```

not sure how to modify this one: 

```
# copy testing imgs
fs::file_copy(
  path = testing_imgs,
  new_path = gsub("/Users/juliavassey/Desktop/photos_classifiers_test/(cats|dogs)/", "data/test/images/\\1", testing_imgs)
)
```

**Comment by juliavassey** [comment] 2019-05-30 22:45
Daniel, I got the matrix of predictions on Inception V3. It gives me 6 classes with numbers (1, 2, 3, 4, 5, 6) if I want them to be names as strings, what should I do? If I modify test_gen by adding classes = c (cats, dogs, etc), the prediction does not work. Any thoughts?
```
test_gen =
  keras::flow_images_from_directory(dirs$test, generator = img_gen,
                                    # Images will be resized to this target size.
                                    target_size = c(img_width, img_height), batch_size = batch_size, color_mode = "rgb", class_mode = "categorical", shuffle = FALSE)
```

**Comment by juliavassey** [comment] 2019-05-30 22:46
Also, model evaluation gives an error: 

 eva <- evaluate_generator(new_model3, test_gen, steps = 10)

Hide Traceback
Rerun with Debug
Error in py_call_impl(callable, dots$args, dots$keywords) :
 ValueError: Error when checking target: expected dense_1 to have shape (6,) but got array with shape (1,)

**Comment by dfalbel** [comment] 2019-05-31 10:34
You can take a look at this tutorial in the TensorFlow blog which explains in more detail the `image_data_generators` and all of it's arguments: https://blogs.rstudio.com/tensorflow/posts/2017-12-14-image-classification-on-small-datasets/

There's also this page on the docs describing all arguments of `flow_images_from_directory`: https://tensorflow.rstudio.com/keras/reference/flow_images_from_directory.html

I already sent you 2 working examples but I can't debug the changes you are making without a fully reproducible example. For instance, I don't know what is `new_model3` in the code above. 

Please, provide some code that I can copy & paste and find the same error you are having.

**Closed** 2019-06-05 08:28 UTC
Labels: analysis
