### ISSUE TITLE
Unified install of tensorflow/keras for MacOS (M1, x86_64), Win (x86_64) and Linux (x86_64)

### ISSUE THREAD

**Issue by bnaras** [rstudio/keras#1244] opened 2021-07-08 17:57 UTC
For the new edition of ISLR (https://www.statlearning.com/) I have a set of installation instructions that work in a unified way with the following specs:

|os      |arch   |python |numpy  |scipy |tensorflow |pillow |installer                                                                                       |
|:-------|:------|:------|:------|:-----|:----------|:------|:-----------------------------------------------------------------------------------------------|
|darwin  |x86_64 |3.9.5  |1.19.5 |1.7.0 |2.4.1      |8.2.0  |https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-MacOSX-x86_64.sh   |
|darwin  |arm64  |3.9.5  |1.19.5 |1.7.0 |2.5.0      |8.2.0  |https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-MacOSX-arm64.sh    |
|windows |x86_64 |3.9.5  |1.19.5 |1.7.0 |2.5.0      |8.2.0  |https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Windows-x86_64.exe |
|linux   |x86_64 |3.9.5  |1.19.5 |1.7.0 |2.5.0      |8.2.0  |https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh    |

This took quite an effort to get right and tested and so I am happy to contribute these to save others the hassle. They involve some modified versions of the `reticulate` internal functions.  (Also involves what I believe is a bug fix for the `reticulate:::conda_create` function with `pip=TRUE` option).  So let me know if you'd like to have them. Better still, I'd like to see them incorporated officially, so that I don't have to maintain this.

**Comment by t-kalinowski** [comment] 2021-07-09 13:43
Hi, thanks for filing.
I'm looking forward to the next edition of ISLR! 
In general we welcome contributions, but I'm a little unclear about what you're proposing here. Perhaps if you share some snippets it will help me understand? It sounds like maybe you're proposing a PR to reticulate.

**Comment by bnaras** [comment] 2021-07-09 15:19
The new edition of ISLR has several labs based on `tensorflow/keras` and it is our experience that installing `tensorflow/keras` is a major problem. It is hard to find a combination that works on common platforms as some of the issues posted even here (e.g. #1165 ) show. There are really no official options for Mac M1, and on windows, the default instructions lead to a combination of `python==3.7` and `tensorflow==1.4`, quite old. We've struggled for over a year to provide easy instructions for the book readers. I attach it here (where the steps 0 and 5 can be substituted with `source("install.R")` until `ISLR2` is on CRAN ).  So my comment is really that a tried and tested solution is sorely needed where my hacks are not required and the standard procedures often fail. It is surely possible that you already have something in the queue and I am not aware of it.  I can surely roll the issue I found for `reticulate` into a PR, but there is a larger problem as well. This is why I posted the matrix above.

**Comment by gilbertocamara** [comment] 2021-07-11 14:04
Thanks, @bnaras! Your contribution is most appreciated and much needed for all those that want to run machine learning and R in the new Mac M1 machines. I had been trying for weeks. Allow me to suggest that you send a message to the mailing list of the R special interest group on MAC OS: https://stat.ethz.ch/mailman/listinfo/r-sig-mac. You might also want to consider adding this information to the ISLR book page.

**Comment by t-kalinowski** [comment] 2021-07-12 17:33
Hi,

Thank you for raising this issue. I wasn't aware that installation was causing such difficulties, and I want to do what I can to make it easier. 

Tensorflow installation has always been more involved than a traditional R package. Because of this, `tensorflow::install_tensorflow()` (and `keras::install_keras()`) attempt to be a robust and convenient installer that smooths over all the differences between platforms and user environments. If they are failing to do the job of installing tensorflow on a supported platform, then that's a clear bug and I would be eager to get it fixed.

Regarding installation of special builds of tensorflow optimized for macOS on M1 (or other future Apple Silicon chips), please let's move the discussion to https://github.com/rstudio/tensorflow/issues/474 .

Regarding windows: I just tried on a fresh windows 10 installation with R 4.1 `keras::install_keras()`, and it pulled down Tensorflow 2.5.0 (the latest), on python 3.7.10. I am surprised to hear that you're getting tensorflow version 1 still. Can you maybe post some additional system information to track this down?

We have automated integration tests that run across all the supported platforms ([Ubuntu, macOS, Win10](https://github.com/rstudio/keras/blob/master/.github/workflows/main.yaml#L16)), and those are all passing currently. If you are experiencing issues consistently, then perhaps the first task is for me to expand the CI test suite. Can you please help me identify platforms/environments where installation is consistently failing?

In regards to installation of specific versions of packages (e.g., for a book lab), I would expect that giving users something like this should work:
```R
tensorflow::install_tensorflow(
  version = "2.5",
  method="conda",
  conda_python_version = "3.9",
  extra_packages = c(
    "numpy==1.19.5",
    "scipy==1.7.0",
    "pillow==8.2.0"))
```
If the above fails on some platforms, then that's a bug and I would be happy to work with you to get it fixed. (However, bugs that arise from specific version/platform mismatches generally need be fixed upstream and are out of our control).

The ability to install specific versions of packages is an important feature for reproducibility (e.g. a book lab). However, I think the default should be that `tensorflow::install_tensorflow()` always pulls down the latest release version of everything. I would expect that on all platforms today, running `tensorflow::install_tensorflow()` would pull down tensorflow version 2.5.0.

Thank you again for raising this.

**Comment by bnaras** [comment] 2021-07-12 22:40
Hi Tomasz, Thank you very much for your helpful and detailed reply.  Yes, I was aware of being able to specify the various versions of `python`, `conda`, and `python` packages, but what I was pointing out was this: the precise combination of versions of these would be hard to find for a person just starting to use the `keras` R package. I ended up doing a large factorial experiment to figure out combinations that would work for exercises in the JJ's book for example (`pillow` was a painful one especially as it is imported as `PIL`). 

What would be very useful is that the matrix that is being run with Github actions is published on this repo as the _officially tested combination_. Then, one could even have a function `keras::install_suggested_config()` that pulls that combination (for the user os and arch) and creates an environment for a user in one shot via the command above.

I will move the discussion of Mac M1 to the [`rstudio/tensorflo#474`](https://github.com/rstudio/tensorflow/issues/474) as you suggest.

**Comment by gilbertocamara** [comment] 2021-07-13 12:19
Hi Tomasz, the default installation of keras, tensorflow and reticulate is failing in Mac M1 machines. This installation relies on miniconda, which does not have a version for Mac M1. So please consider that novice R users will not be able to use keras on Mac M1 machines and thus please keep the issue open.

**Comment by bnaras** [comment] 2021-07-13 14:27
Hi Gilberto, Thank you for your comments.  I hope you are able to use the instructions for M1 for yourself.  It should work, else let me know.  I was actually thinking of setting up a Repo with Github actions to publish the nightly tested configs for all, but it looks like Tomasz and others have the beginnings of it anyway.  Also, the `ISLR2` package will be on CRAN as well as the instructions.

**Comment by t-kalinowski** [comment] 2021-07-27 16:55
@bnaras thank you for opening this issue, it was the catalyst for the work that led to https://github.com/rstudio/keras/pull/1251 and  https://github.com/rstudio/tensorflow/pull/476.

As part of the refactoring, I aimed to simplify and remove the use of extra configuration variables like RETICULATE_AUTOCONFIGURE as much as possible. I also added a section of code where, from a maintenance perspective, it should be easy to constrain versions of keras's soft python dependencies like Pillow: https://github.com/rstudio/keras/blob/8ff87913aee20148bed577ed5c7183e72fd98631/R/install.R#L79-L86

Sadly, M1 is not something that we can officially support yet. I did add a sections in `?install_keras` pointing users to the experimental builds offered by apple + miniforge. The intent is to revisit this question M1 support towards the end of the year (hopefully by then apple metal plugins will have been merged into the tensorflow mainline, and github actions runners will offer images running on M1).

I'm going to close the issue, but please feel free to respond on this thread if you have additional questions or concerns related to tensorflow installation.

**Closed by t-kalinowski** 2021-07-27 16:55 UTC
Labels: apple silicon

**Comment by t-kalinowski** [comment] 2021-12-06 21:15
The development version of `tensorflow::install_tensorflow()` (and `keras::install_keras()`) now has support for Arm Macs.
This should setup a working Tensorflow installation:
```R
remotes::install_github("rstudio/tensorflow")
reticulate::install_miniconda()
tensorflow::install_tensorflow()
```
Please file an issue if you encounter errors!
