### ISSUE TITLE
Unexpected error calling Py_AddPendingCall

### ISSUE THREAD

**Issue by MatHaligan** [rstudio/keras#148] opened 2017-10-06 08:45 UTC
Using Keras with tensorflow (cpu and gpu) version , sometimes, after a while, the following error is displayed during training 
"Unexpected error calling Py_AddPendingCall"

rstudio is then blocked in "running state". Nothing else to do except using "Terminate R"

**Comment by jjallaire** [comment] 2017-10-06 11:31
Thanks very much for reporting this! It would be ideal if I could reproduce this one locally, or at a minimum if you could provide me with a version of the code for the training script that exhibits this behavior.

My strong guess would be that you are using `fit_generator()` to train the model? In that case it's possible that the background training data generation is getting way in front of the foreground training operation. Does this sound like a possibility?

I have a couple of ways I think I can approach fixing this but getting some more code / context from you will give me a better idea.

**Comment by jjallaire** [comment] 2017-10-06 12:20
I've checked in a speculative fix for this to the reticulate repo. To try this out install reticulate from GitHub with:

```r
devtools::install_github("rstudio/reticulate")
```

Note that if you are on Windows you need to do this from a completely fresh session or there may be DLL in use issues during the installation.

Let me know if this addresses the issue as well as the other repro context I requested if you can.

**Comment by MatHaligan** [comment] 2017-10-08 09:27
I am working with windows. The installation of the rstudio/reticulate seems to have solved the problem.
Sorry for the inconvenience.

**Comment by jjallaire** [comment] 2017-10-08 11:27
That's great to hear! Thanks again for reporting the issue, glad we were able to sort it out.

**Closed by jjallaire** 2017-10-08 11:27 UTC

**Comment by MatHaligan** [comment] 2017-10-08 12:13
Hum I was too quick for the testing. The problem happened again. what info would you need ?

I am using fit_generator as you mentioned...

model %>% 
  fit_generator(sampling_generator(images.rgb_training, images.lab_training, batch_size = batch_size), 
                steps_per_epoch = length(images.rgb_training) / batch_size, epochs = 200,
                validation_data = list(validation_x, validation_y))

**Comment by jjallaire** [comment] 2017-10-08 21:42
Do you get the same error message: "Unexpected error calling Py_AddPendingCall"

If so, that means that the update to reticulate was *not successful* since that error string is no longer used.

To ensure a successful update you need to exit all versions of R, start a fresh session with a clean/empty environment, and then attempt the update.
