### ISSUE TITLE
Error in py_call_impl(callable, dots$args, dots$keywords) : UnboundLocalError: local variable 'a' referenced before assignment

### ISSUE THREAD

**Issue by ChristelSwift** [rstudio/keras#693] opened 2019-03-08 08:50 UTC
hi there,

i'm trying to reproduce the tensorflow/rstudio text classification tutorial (https://tensorflow.rstudio.com/keras/articles/tutorial_basic_text_classification.html) but when i get to the "train the model" step, i get this error message:

    Error in py_call_impl(callable, dots$args, dots$keywords) : UnboundLocalError: local variable 'a' referenced before assignment

Here's my session info:

R version 3.5.2 (2018-12-20)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.3

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bindrcpp_0.2.2   purrr_0.3.1      ggplot2_3.1.0    dplyr_0.7.8      keras_2.2.4.9001

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0             rstudioapi_0.9.0       knitr_1.21             bindr_0.1.1           
 [5] whisker_0.3-2          magrittr_1.5           munsell_0.5.0          tidyselect_0.2.5      
 [9] colorspace_1.4-0       lattice_0.20-38        R6_2.4.0               rlang_0.3.1           
[13] plyr_1.8.4             tools_3.5.2            grid_3.5.2             gtable_0.2.0          
[17] xfun_0.4               withr_2.1.2            tfruns_1.4             lazyeval_0.2.1        
[21] yaml_2.2.0             assertthat_0.2.0       tibble_2.0.1           crayon_1.3.4          
[25] tensorflow_1.10.0.9000 Matrix_1.2-15          base64enc_0.1-3        zeallot_0.1.0         
[29] glue_1.3.0             compiler_3.5.2         pillar_1.3.1           scales_1.0.0          
[33] generics_0.0.2         reticulate_1.11.1-9000 jsonlite_1.6           pkgconfig_2.0.2       

Any idea why this tutorial woulnd't work on my machine?

many thanks

**Comment by jjallaire** [comment] 2019-03-08 11:06
Same issue as is being seen here: https://github.com/rstudio/keras/issues/693

I think there is a problem w/ TensorFlow 1.13 and the R Keras package. Try installing an earlier version of TensorFlow with:

```r
install_tensorflow(version = "1.12")
```

**Comment by jjallaire** [comment] 2019-03-08 11:06
cc @javierluraschi

**Comment by ChristelSwift** [comment] 2019-03-11 11:02
> Same issue as is being seen here: #693
> 
> I think there is a problem w/ TensorFlow 1.13 and the R Keras package. Try installing an earlier version of TensorFlow with:
> 
> ```r
> install_tensorflow(version = "1.12")
> ```

that worked!  thank you

**Comment by ChristelSwift** [comment] 2019-03-11 11:07
> Same issue as is being seen here: #693
> 
> I think there is a problem w/ TensorFlow 1.13 and the R Keras package. Try installing an earlier version of TensorFlow with:
> 
> ```r
> install_tensorflow(version = "1.12")
> ```

that worked!  thank you

**Comment by skeydan** [comment] 2019-03-15 19:26
also fixed by https://github.com/rstudio/keras/pull/692

I think we could revert to installing 1.13 by default now

**Closed by skeydan** 2019-03-15 19:26 UTC

**Comment by NWPope** [comment] 2019-04-02 21:32
Just now had the same issue- reverting to 1.12 fixed the problem

**Comment by xytangtang** [comment] 2019-04-24 23:50
I got the same error when running k_clear_session(). The version of tensorflow is 1.12:
> tensorflow::tf_version()
[1] ‘1.12’

Here is my code
`inputs <- layer_input(list(10))
outputs <- inputs %>% layer_dense(1)
mymodel <- keras_model(inputs, outputs)
mymodel %>% compile(loss="mean_squared_error", optimizer="sgd")
k_clear_session()`

Here is my session info:

R version 3.3.3 (2017-03-06)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS  10.13.4

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] keras_2.1.6.9001 ProcData_0.1.0  

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.16          roxygen2_6.0.1        lattice_0.20-35      
 [4] digest_0.6.15         zeallot_0.0.6         withr_2.1.2          
 [7] commonmark_1.5        grid_3.3.3            R6_2.2.2             
[10] jsonlite_1.5          magrittr_1.5          tfruns_1.1           
[13] stringi_1.1.7         whisker_0.3-2         Matrix_1.2-14        
[16] xml2_1.2.0            reticulate_1.7.1      devtools_1.13.5      
[19] tools_3.3.3           stringr_1.3.0         yaml_2.1.18          
[22] base64enc_0.1-3       tensorflow_1.5.0.9001 memoise_1.1.0

**Comment by dfalbel** [comment] 2019-05-31 11:22
This is a bug related to TensorFlow v1.13.1 and Python 3.7. The options to fix are:

* Update to TensorFlow 1.14 - currently nightly (`install_tensorflow(version = "nightly")`)
* Downgrading python version to 3.6. 
* Downgrading TensorFlow version to 1.12 (`install_tensorflow(version = "1.12.0")`)

**Comment by skeydan** [comment] 2019-05-31 12:39
Great you were able to reproduce! Then it must be an OSX thing. I can't reproduce on linux, using TF 1.13.1 with Python 3.7.

I'll attach the test code (so any further tests don't require copy-pasting from the tutorial).

What I _had_ to do though, to make that run on 1.13, was downgrading numpy as per 
https://github.com/rstudio/keras/issues/765

```
reticulate::use_condaenv("1.13", required=T)
library(keras)
library(dplyr)
library(ggplot2)
library(purrr)

imdb <- dataset_imdb(num_words = 10000)

c(train_data, train_labels) %<-% imdb$train
c(test_data, test_labels) %<-% imdb$test

word_index <- dataset_imdb_word_index()
word_index_df <- data.frame(
  word = names(word_index),
  idx = unlist(word_index, use.names = FALSE),
  stringsAsFactors = FALSE
)

# The first indices are reserved  
word_index_df <- word_index_df %>% mutate(idx = idx + 3)
word_index_df <- word_index_df %>%
  add_row(word = "<PAD>", idx = 0)%>%
  add_row(word = "<START>", idx = 1)%>%
  add_row(word = "<UNK>", idx = 2)%>%
  add_row(word = "<UNUSED>", idx = 3)

word_index_df <- word_index_df %>% arrange(idx)

decode_review <- function(text){
  paste(map(text, function(number) word_index_df %>%
              filter(idx == number) %>%
              select(word) %>% 
              pull()),
        collapse = " ")
}

train_data <- pad_sequences(
  train_data,
  value = word_index_df %>% filter(word == "<PAD>") %>% select(idx) %>% pull(),
  padding = "post",
  maxlen = 256
)

test_data <- pad_sequences(
  test_data,
  value = word_index_df %>% filter(word == "<PAD>") %>% select(idx) %>% pull(),
  padding = "post",
  maxlen = 256
)

x_val <- train_data[1:10000, ]
partial_x_train <- train_data[10001:nrow(train_data), ]

y_val <- train_labels[1:10000]
partial_y_train <- train_labels[10001:length(train_labels)]

vocab_size <- 10000

model <- keras_model_sequential()
model %>% 
  layer_embedding(input_dim = vocab_size, output_dim = 16) %>%
  layer_global_average_pooling_1d() %>%
  layer_dense(units = 16, activation = "relu") %>%
  layer_dense(units = 1, activation = "sigmoid")

model %>% summary()

model %>% compile(
  optimizer = 'adam',
  loss = 'binary_crossentropy',
  metrics = list('accuracy')
)

history <- model %>% fit(
  partial_x_train,
  partial_y_train,
  epochs = 1,
  batch_size = 512,
  validation_data = list(x_val, y_val),
  verbose=1
)

```

**Comment by javierluraschi** [comment] 2019-05-31 23:33
Another potential workaround from @dfalbel would be to run the following from the Anaconda prompt:

```
conda activate r-tensorflow
pip install tensorflow
```

**Comment by monitarb** [comment] 2020-10-27 04:41
Hope this helps!
I had the same error, but in my case it was a multi-classification problem, so my loss function was: **categorical_crossentropy**.
_Don't undestand why_, but problem was solved by changing my loss function to: **sparse_categorical_crossentropy**

**Comment by ReyCJ** [comment] 2021-03-06 12:48
This worked for me, I just installed GPU version of Tensorflow.

library(tensorflow)
install_tensorflow(version = "gpu")

**Comment by PeerW** [comment] 2021-04-15 13:25
@monitarb I had the same issue and changing the loss function to sparse_categorical_crossentropy fixed it.
Did you ever figure out why this makes the model work?
