### ISSUE TITLE
Writing custom layer for Keras - NULL problem

### ISSUE THREAD

**Issue by tomasj12** [rstudio/keras#811] opened 2019-06-09 21:40 UTC
Hi, i am trying to create my own Layer in Keras, here is my code:

```r
OwnLayer <- R6Class('OwnLayer',
      
        inherit = KerasLayer,
        public = list(
            
            centers = NULL,
            output_dim = 4,

            initialize = function(output_dim) {
              
              self$output_dim <- output_dim
              
            },

            build = function(input_shape) {
              
                self$centers <- self$add_weight(
                                  name = 'centers',
                                  shape = list(input_shape[[2]],self$output_dim),
                                  initializer = initializer_random_uniform(0,1),
                                  trainable = TRUE)
                                  
              
              
            },
            
            call = function(x) {
              
                k_exp(- (x - self$centers)^2)
              
              
            },
            
            compute_output_shape = function(input_shape) {
              list(input_shape[[1]], self$output_dim)
            }
        
        
      ))


layer_own <- function(object,output_dim, name = NULL,trainable = TRUE) {
  
    create_layer(OwnLayer, object, list(
          output_dim = as.integer(output_dim),
          name = name,
          trainable = trainable
  ))
  
model1 <- keras_model_sequential() 
  
}
```

and after this:

```r
model1 %>% 
  layer_dense(units = 10, activation = 'relu', input_shape = 1) %>%
  layer_own(output_dim = 32)
```

R throws me an error:

```r
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  RuntimeError: Evaluation error: unused argument (NULL).
```
When i debugged - it looks like, it is problem in dost$keywords - but i do not know how to fix it.

Here is my r Session

```r
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

locale:
[1] LC_COLLATE=Slovak_Slovakia.1250  LC_CTYPE=Slovak_Slovakia.1250   
[3] LC_MONETARY=Slovak_Slovakia.1250 LC_NUMERIC=C                    
[5] LC_TIME=Slovak_Slovakia.1250    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] R6_2.4.0          tensorflow_1.13.1 keras_2.2.4.1    

loaded via a namespace (and not attached):
 [1] compiler_3.6.0  magrittr_1.5    Matrix_1.2-17   generics_0.0.2  tools_3.6.0    
 [6] whisker_0.3-2   base64enc_0.1-3 Rcpp_1.0.1      reticulate_1.12 grid_3.6.0     
[11] zeallot_0.1.0   jsonlite_1.6    tfruns_1.4      lattice_0.20-38
```

**Comment by dfalbel** [comment] 2019-06-10 14:16
I think the problem is that your `call` method does not have the `mask` argument, even if it's not used. The methods signatures must be the same as the example available here: https://tensorflow.rstudio.com/keras/articles/custom_layers.html#keraslayer-r6-class

**Comment by tomasj12** [comment] 2019-06-12 09:02
Hi @dfalbel , thanks for your help, but right now, i have different problem. Here is my code again:

```r
OwnLayer <- R6Class('OwnLayer',
                    inherit = KerasLayer,
                    public = list(
                      output_dim = NULL,
                      betas = NULL,
                      centers = NULL,
                      centers_start = NA,
                      betas_start = NA,
                      input_shape = NA,

                      initialize = function(output_dim, betas_start, input_shape) {
                        self$output_dim <- output_dim
                        self$betas_start <- betas_start
                        self$input_shape <- input_shape
                        #
                        #  if (is.null(centers)) {
                        #
                        #
                        #   self$centers_start <- initializer_random_uniform(0,1)
                        #
                        # } else {
                        #
                        #   self$centers_start <- centers
                        #
                        # }
                      },
                      build = function(input_shape) {
                        self$centers <- self$add_weight(
                          name = 'centers',
                          shape = list(self$output_dim,self$input_shape[[2]]),
                          initializer = initializer_random_uniform(0,1),
                          trainable = TRUE)
                        self$betas <-  self$add_weight(
                          name = 'betas',
                          shape = list(self$output_dim),
                          initializer = initializer_constant(self$betas_start),
                          trainable = TRUE)
                      },
                      call = function(x, mask = NULL) {
                        k_exp(- self$betas * (x - self$centers)^2)
                      },
                      compute_output_shape = function(input_shape) {
                        list(self$input_shape[[1]], self$output_dim)
                      }
                    ))

layer_own <- function(object,output_dim,input_shape,betas_start = 4,name = NULL,trainable = TRUE) {
  create_layer(OwnLayer, object, list(
    output_dim = as.integer(output_dim),
    name = name,
    betas_start = betas_start,
    # centers = centers,
    trainable = trainable,
    input_shape = input_shape
  ))
}

model1 <- keras_model_sequential()
model1 %>%
  layer_own(output_dim = 10, input_shape = 10)%>%
  layer_dense(units = 1)

```
Here i have problem with input_shape. It throws me error like this:

```r
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: 'float' object is not iterable
```

I do not know, if i need to create a new logic, how to handle my own input_shape - because if i sent just integer - it should be problem in ,,build'' with subscripts. Because when i look on some python codes, there is no problem with this, but in R  i have problem with this input_shape.

**Comment by skeydan** [comment] 2019-06-12 12:54
Your custom code presupposes an input that is 2-dimensional _excluding_ the batch dimension.
Not sure if you want that, but if yes, `input_shape` should be specified 2d too, e.g.

```
model1 %>%
  layer_own(output_dim = 10, input_shape = c(10, 10))%>%
  layer_dense(units = 1)
```

E.g. if you compare https://tensorflow.rstudio.com/keras/articles/custom_layers.html, there the example input is effectively 3d too (effectively meaning, including the batch dimension).

**Comment by dfalbel** [comment] 2019-06-12 14:28
I would also try to explicitly convert the output shape to integers using `as.integer`. By default, R will store all values as doubles and this could be the cause of the error.

**Comment by dfalbel** [comment] 2019-06-18 20:33
I am closing this issue. Please reopen if you need additional help.

**Closed by dfalbel** 2019-06-18 20:33 UTC
Labels: question
