### ISSUE TITLE
Error "missing value where TRUE/FALSE needed" in R printed in console when calling Tensorflow/Keras

### ISSUE THREAD

**Issue by OthmanElHammouchi** [rstudio/keras#1331] opened 2022-05-07 15:37 UTC
I'm having an issue where loading Tensorflow in R results in a permanent error message below the prompt saying "missing value where TRUE/FALSE needed". After this, everything seems to be working fine, but I can't figure out what's causing this or how to get rid of it. I have Python, Tensorflow, Keras and the necessary R packages (interfaces and reticulate) installed in the same conda environment and am using the VS Code editor with the radian terminal (although vanilla R yields the same problem). Curiously, the issue does not manifest when running the code in a seperate terminal outside of VS Code. Any idea what could be causing this?

Output:

```
r$> input <- layer_input(shape = c(1), dtype = "string")
Loaded Tensorflow version 2.6.0
missing value where TRUE/FALSE needed
```

**Comment by tomlue** [comment] 2022-10-01 01:40
Some things I tried that didn't work include:
1. disabling `R Debugger` vscode extension
2. disabling `REditorSupport` vscode extension
3. reinstall keras with `keras::install_keras()`
4. reinstall tensorflow with `tensorflow::install_tensorflow()`

One thing that did work was:
1. creating a new conda environment for reticulate
2. closing vscode and opening a new vscode

It's possible only (2) was required, but I can't test now that the issue isn't occurring any longer.

**Comment by t-kalinowski** [comment] 2022-10-02 14:15
If I recall correctly, this is already fixed in the release version (and unfortunately this issue should have been closed with a link to the patch at that time). If you update the R package, does it fix the issue? `install.packages("keras")`

**Comment by tomlue** [comment] 2022-10-02 17:26
I am on version 2.9.0 and the error is persisting. To reproduce this issue I did:

```
# open vscode and a terminal
conda create --name testenv python=3.9
conda activate testenv
R # start R in terminal
reticulate::use_condaenv('testenv')
keras::install_keras()
tensorflow::install_tensorflow()
```
and then
```
> library(keras)
> library(tensorflow)
> input <- layer_input(c(100),name='test')
missing value where TRUE/FALSE needed> 
```
and I get the output

**Comment by t-kalinowski** [comment] 2022-10-02 18:57
Are you starting R from a shell with an activated condaenv? I think that will likely lead to problems. It's recommended that if R is not originating from conda, it's better to start R normally (outside of a conda shell), and then let reticulate attach to the conda env on it's own.

My best guess is that conda is installing an outdated version of R or the R package "keras" here. A `sessionInfo()` might confirm this.

**Comment by tomlue** [comment] 2022-10-02 23:27
I don't think the issue is related to running R in a conda environment, running `packageVersion('keras')` in the running R terminal returns 2.9.0 and R is not installed in my conda environment.

It seems likely that the issue occurs due to something in the loading of the reditorsupport extension. Especially since the issue only occurs in vscode, and the issue dissappears when I remove the below from ~/.vscode-R/init.R 
```
local(source("~/.vscode/extensions/reditorsupport.r-2.5.3/R/session/init.R", chdir = TRUE, local = TRUE))
```

I'm ok with this getting closed, as it seems possible it is not a keras specific issue, and more likely and reditorsupport issue.

**Closed** 2022-10-03 13:49 UTC
