### ISSUE TITLE
Model input shape in word embedding example

### ISSUE THREAD

**Issue by xiongjun926** [rstudio/keras#740] opened 2019-04-13 12:59 UTC
Hi, 

Trying the word embedding example on this post: https://www.r-bloggers.com/word-embeddings-with-keras/. Wonderful example while can not get it work on both windows and unbuntu:

**code (the same as the post):**

```
download.file("https://snap.stanford.edu/data/finefoods.txt.gz", "finefoods.txt.gz")
library(readr)
library(stringr)
reviews <- read_lines("finefoods.txt.gz") 
reviews <- reviews[str_sub(reviews, 1, 12) == "review/text:"]
reviews <- str_sub(reviews, start = 14)
reviews <- iconv(reviews, to = "UTF-8")
head(reviews, 2)
library(keras)
tokenizer <- text_tokenizer(num_words = 20000)
tokenizer %>% fit_text_tokenizer(reviews)

library(reticulate)
library(purrr)
skipgrams_generator <- function(text, tokenizer, window_size, negative_samples) {
  gen <- texts_to_sequences_generator(tokenizer, sample(text))
  function() {
    skip <- generator_next(gen) %>%
      skipgrams(
        vocabulary_size = tokenizer$num_words, 
        window_size = window_size, 
        negative_samples = 1
      )
    x <- transpose(skip$couples) %>% map(. %>% unlist %>% as.matrix(ncol = 1))
    y <- skip$labels %>% as.matrix(ncol = 1)
    list(x, y)
  }
}

embedding_size <- 128  # Dimension of the embedding vector.
skip_window <- 5       # How many words to consider left and right.
num_sampled <- 1       # Number of negative examples to sample for each word.

input_target <- layer_input(shape = 1)
input_context <- layer_input(shape = 1)

embedding <- layer_embedding(
  input_dim = tokenizer$num_words + 1, 
  output_dim = embedding_size, 
  input_length = 1, 
  name = "embedding"
)

target_vector <- input_target %>% 
  embedding() %>% 
  layer_flatten()

context_vector <- input_context %>%
  embedding() %>%
  layer_flatten()

dot_product <- layer_dot(list(target_vector, context_vector), axes = 1)
output <- layer_dense(dot_product, units = 1, activation = "sigmoid")

model <- keras_model(list(input_target, input_context), output)
model %>% compile(loss = "binary_crossentropy", optimizer = "adam")

model %>%
  fit_generator(
    skipgrams_generator(reviews, tokenizer, skip_window, negative_samples), 
    steps_per_epoch = 100000, epochs = 5
  )

**Error:** 

13. | stop(structure(list(message = "ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 2 array(s), but instead got the following list of 1 arrays: [array([[[ 2485],\n        [  261],\n        [   38],\n        ...,\n        [   38],\n        [    1],\n        [   12]],\n\n       [[ 6959],\n        [   53],\n        [10595],\n        ...,\n        [ 2485],\n ...",      call = py_call_impl(callable, dots$args, dots$keywords),      cppstack = structure(list(file = "", line = -1L, stack = "C++ stack not available on this system"), .Names = c("file",      "line", "stack"), class = "Rcpp_stack_trace")), .Names = c("message",  ...
-- | --
```

```
**Session Info:**

sessionInfo() R version 3.4.3 (2017-11-30) Platform: x86_64-w64-mingw32/x64 (64-bit) Running under: Windows >= 8 x64 (build 9200)  Matrix products: default  locale: [1] LC_COLLATE=Chinese (Simplified)_China.936  LC_CTYPE=Chinese (Simplified)_China.936    LC_MONETARY=Chinese (Simplified)_China.936 LC_NUMERIC=C                               [5] LC_TIME=Chinese (Simplified)_China.936      attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       other attached packages: [1] purrr_0.2.4            reticulate_1.12.0-9000 stringr_1.2.0          readr_1.1.1            keras_2.2.4.1           loaded via a namespace (and not attached):  [1] Rcpp_1.0.1        whisker_0.3-2     magrittr_1.5      hms_0.4.1         devtools_1.13.5   lattice_0.20-35   R6_2.2.2          rlang_0.1.6       tools_3.4.3       grid_3.4.3        withr_2.1.1       [12] tfruns_1.4        yaml_2.1.16       digest_0.6.13     tibble_1.4.1      tensorflow_1.13.1 Matrix_1.2-12     base64enc_0.1-3   zeallot_0.1.0     memoise_1.1.0     stringi_1.1.6     compiler_3.4.3    [23] pillar_1.0.1      generics_0.0.2    jsonlite_1.6      pkgconfig_2.0.1
--
 
> | >
>
```
Any help greatly appreciated.

**Comment by dfalbel** [comment] 2019-04-15 14:10
Can you try installing the dev version of reticulate with:

```
devtools::install_github("rstudio/reticulate")
```

Let me know if the error persists.

**Comment by xiongjun926** [comment] 2019-04-15 16:47
Done. Error still the same:
devtools::install_github("rstudio/reticulate",force=T)
Downloading GitHub repo rstudio/reticulate@master
✔  checking for file ‘/tmp/RtmpI65PPM/remotes36c5edf69bd/rstudio-reticulate-f3179ab/DESCRIPTION’ ...
─  preparing ‘reticulate’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘reticulate_1.12.0-9000.tar.gz’
   
Installing package into ‘/home/hadoop/R/x86_64-pc-linux-gnu-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package ‘reticulate’ ...
** libs
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/hadoop/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/hadoop/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c event_loop.cpp -o event_loop.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/hadoop/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c libpython.cpp -o libpython.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/hadoop/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c output.cpp -o output.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/hadoop/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c python.cpp -o python.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/hadoop/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c readline.cpp -o readline.o
g++ -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o reticulate.so RcppExports.o event_loop.o libpython.o output.o python.o readline.o -L/usr/lib/R/lib -lR
installing to /home/hadoop/R/x86_64-pc-linux-gnu-library/3.5/reticulate/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (reticulate)

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 2 array(s), but instead got the following list of 1 arrays: [array([[ 133],
       [  84],
       [   3],
       ...,

**Comment by dfalbel** [comment] 2019-05-24 19:50
I have worked on a fix for this here: https://github.com/rstudio/keras/pull/788 
You can install this version of keras by running:

`devtools::install_github("rstudio/keras#788")`

I also changed the generator to something like this:

```
skipgrams_generator <- function(text, tokenizer, window_size, negative_samples) {
  gen <- texts_to_sequences_generator(tokenizer, sample(text))
  function() {
    
    while(TRUE) {
      nxt <- generator_next(gen)
      if (length(nxt) > 1)
        break
    }
    
    skip <- nxt %>%
      skipgrams(
        vocabulary_size = tokenizer$num_words, 
        window_size = window_size, 
        negative_samples = 1
      )
    x <- transpose(skip$couples) %>% map(. %>% unlist %>% as.matrix(ncol = 1))
    y <- skip$labels %>% as.matrix(ncol = 1)
   
    list(x, y)
  }
}
```

Let me know if you can reproduce it now.

**Closed** 2019-05-27 12:22 UTC
Labels: bug

**Comment by Sophia0616** [comment] 2019-06-25 01:17
Hi, I got the same error but for output: 
`Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Error when checking model target: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 4 array(s), but instead got the following list of 1 arrays: [array([[ 0.01591682,  0.01753547, -0.00334716, ...,  0.03716933,`

so I installed from GitHub but got this error instead:

`Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: __init__() got an unexpected keyword argument 'r_on_predict_begin'` 

:'(

**Comment by Sophia0616** [comment] 2019-06-25 02:00
fit() also stopped working after I installed from Github, so I figured the error wasn't from this fix. I went and added this fix to the cran/v2.2.4 branch and installed that and I'm happy to report that fit_generator is now working with neither of the two errors. Although I'm still not sure where the error is coming from. 

Hope this is somewhat helpful.

**Comment by dfalbel** [comment] 2019-06-25 08:32
@Sophia0616 what's your TensorFlow version? I think you may need to update your TensorFlow python installation. You can see that with `tf_config()`

**Comment by henry090** [comment] 2019-08-05 15:34
@dfalbel Hi, cannot run due to error.

```
R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] purrr_0.3.2        reticulate_1.13    keras_2.2.4.1.9001 dplyr_0.8.3        vroom_1.0.2       

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2        rstudioapi_0.10   whisker_0.3-2     magrittr_1.5      tidyselect_0.2.5 
 [6] lattice_0.20-38   R6_2.4.0          rlang_0.4.0       stringr_1.4.0     tools_3.6.0      
[11] parallel_3.6.0    grid_3.6.0        withr_2.1.2       tfruns_1.4        assertthat_0.2.1 
[16] tibble_2.1.3      crayon_1.3.4      tensorflow_1.14.0 Matrix_1.2-17     base64enc_0.1-3  
[21] zeallot_0.1.0     glue_1.3.1        stringi_1.4.3     compiler_3.6.0    pillar_1.4.2     
[26] generics_0.0.2    jsonlite_1.6      pkgconfig_2.0.2  
```

```
model %>%
  fit_generator(
    skipgrams_generator(report$text, tokenizer, skip_window, negative_samples), 
    steps_per_epoch = 1000, epochs = 1
  )

15/1000 [..............................] - ETA: 4:40 - loss: 0.6931Error occurred in generator: TypeError: 'int' object is not iterable

Detailed traceback: 
  File "/Users/turgutabdullayev/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/keras_preprocessing/sequence.py", line 197, in skipgrams
    for i, wi in enumerate(sequence):

WARNING: Logging before flag parsing goes to stderr.
W0805 19:30:12.800543 4614043072 training_generator.py:251] Your dataset iterator ran out of data; interrupting training. Make sure that your iterator can generate at least `steps_per_epoch * epochs` batches (in this case, 1000 batches). You may need touse the repeat() function when building your dataset.
```


```
tensorflow::tf_version()
[1] ‘2.0’

keras:::keras_version()
[1] ‘2.2.4’
```
