### ISSUE TITLE
Neural Style Transfer Error

### ISSUE THREAD

**Issue by JazOnToast** [rstudio/keras#732] opened 2019-04-07 12:29 UTC
Hi @skeydan !

I am running  [it](https://tensorflow.rstudio.com/keras/articles/examples/eager_styletransfer.html) and getting an error:

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Tensor conversion requested dtype float32 for Tensor with dtype float64:

Is this an error in the code or anaconda maybe? I am a novice but have racked my brain, searched google high and low, and changed the references to Float32 in the code manually, to float64, all to no avail. Looking for any other solution, or suggestion at an impasse! THANKS!!!!

**Comment by dfalbel** [comment] 2019-04-07 13:08
I am not being able to reproduce but I am getting different errors:

I am getting an error here:

```
> nms <- map_chr(model$layers, ~.x$name)
Error: Result 1 must be a single string, not a vector of class `python.builtin.str/python.builtin.basestring/python.builtin.object` and of length 2
Call `rlang::last_error()` to see a backtrace
```

What is strange here is why does `x$name` not get converted automatically to a character.

If I change this line to

```
nms <- map_chr(model$layers, ~as.character(.x$name))
```

I can go a little far, but at this line:

```
> base_image_features <- layer_features[1,,,]
Error in (function (arg, dim)  : is_scalar_integerish(dim) is not TRUE
```

Again, this is the same problem, the dimensions of `layer_features` are not beign convert automatically to integers, and this should be expected:

```
> dim(layer_features)
[3, 400, 1139, 64]
> x <- layer_input(batch_shape = list(3, 10,10))
> dim(x)
[1]  3 10 10
```

This seems related to the same problem in #722 .

**Comment by dfalbel** [comment] 2019-04-07 14:03
Running this with an old enough version of reticulate eg. 

```
devtools::install_github("rstudio/reticulate@f375e8595e0dd4984d9aced953542758342ad9ba")
```

won't give me any erro. My guess is that it was introduced by https://github.com/rstudio/reticulate/pull/259 or https://github.com/rstudio/reticulate/pull/359

@skeydan can you reproduce this?

**Comment by JazOnToast** [comment] 2019-04-07 17:57
Interesting Dfabel, do you think not using the latest reticulate update may be behind the error? 

This is the script I was running, apologies, the eager style transfer, not the plain style transfer, but I will try and run the plain now and revert.

**Comment by JazOnToast** [comment] 2019-04-07 18:13
> I am not being able to reproduce but I am getting different errors:
> 
> I am getting an error here:
> 
> ```
> > nms <- map_chr(model$layers, ~.x$name)
> Error: Result 1 must be a single string, not a vector of class `python.builtin.str/python.builtin.basestring/python.builtin.object` and of length 2
> Call `rlang::last_error()` to see a backtrace
> ```
> What is strange here is why does `x$name` not get converted automatically to a character.
> 
> If I change this line to
> 
> ```
> nms <- map_chr(model$layers, ~as.character(.x$name))
> ```
> I can go a little far, but at this line:
> 
> ```
> > base_image_features <- layer_features[1,,,]
> Error in (function (arg, dim)  : is_scalar_integerish(dim) is not TRUE
> ```
> Again, this is the same problem, the dimensions of `layer_features` are not beign convert automatically to integers, and this should be expected:
> 
> ```
> > dim(layer_features)
> [3, 400, 1139, 64]
> > x <- layer_input(batch_shape = list(3, 10,10))
> > dim(x)
> [1]  3 10 10
> ```
> This seems related to the same problem in #722 .

I got the same error, on this script, was able to reproduce.

**Comment by skeydan** [comment] 2019-04-08 10:03
Hi @dfalbel this definitely is related (to the errors you report): https://github.com/rstudio/keras/issues/619#issuecomment-449330553
(seems like it _does_ come up again so it was good to leave it open ;-))

However I don't find the code you're running in the example referred (https://github.com/rstudio/keras/blob/master/vignettes/examples/eager_styletransfer.R) (and it was replaced by a working version in the non-eager code as per the above issue #619).

However as it seems this keeps cropping up it probably makes sense to investigate more!
Here is a short "manual reprex" that should throw 2 errors and illustrate how list members are not getting converted. Strangely, this snippet _does_ run for me with

```
devtools::install_github("rstudio/reticulate@acb278da12caff6f50d1dcd9e4e54aeaa9100af2")
```

and I don't see any more commits to `conversion.R` from that time period (so are the relevant changes in another file)?

Here's the test code:

```
library(keras)
model <- keras_model_sequential() %>% layer_dense(units = 1, input_shape = 1, name = "layer1")

layer_name <- "layer1"

layer_dict <- model$layers

# Symptom 1
# Error: Result 1 must be a single string, not a vector of class `python.builtin.str/python.builtin.object` 
# and of length 2
names(layer_dict) <- purrr::map_chr(layer_dict , ~.x$name)
# works
names(layer_dict) <- purrr::map_chr(layer_dict , function(x) as.character(x$name))

# Symptom 2
# cannot coerce type 'environment' to vector of type 'list'
x <- layer_dict[[layer_name]]$output
# works
x <- model$get_layer(layer_name)$output 


# Symptom 2 follow-up
shape <- layer_dict[[layer_name]]$output$get_shape()
shape$as_list()
# [None, 1]

# here we get the conversion as expected
shape <- model$get_layer(layer_name)$output$get_shape()
shape$as_list()
```

**Comment by dfalbel** [comment] 2019-04-08 14:58
I think this is the commit causing the issue: https://github.com/rstudio/reticulate/commit/a98ff163ac4fcb743ad4ac9eaff984069a9de258

Probably it's this function: https://github.com/rstudio/reticulate/commit/a98ff163ac4fcb743ad4ac9eaff984069a9de258#diff-8f5039eb2839438bfbe209fa4eb688ddR53

Before this commit, all lists were treated with `py_to_r.default` and now there's a `disable_conversion_scope` that could affect this?

**Comment by skeydan** [comment] 2019-04-08 15:04
Yes I would think so too, but the above test code does not generate errors after 

```
devtools::install_github("rstudio/reticulate@a98ff163ac4fcb743ad4ac9eaff984069a9de258")
```

Could you double-check this?

**Comment by dfalbel** [comment] 2019-04-08 15:30
For me it won't work with 

``` r
library(keras)
model <- keras_model_sequential() %>% layer_dense(units = 1, input_shape = 1, name = "layer1")
class(model$layers[[1]]$name)
#> [1] "python.builtin.str"        "python.builtin.basestring"
#> [3] "python.builtin.object"
sessioninfo::session_info(pkgs = c("reticulate"))
#> ─ Session info ──────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.5.1 (2018-07-02)
#>  os       macOS  10.14.4              
#>  system   x86_64, darwin15.6.0        
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       America/Sao_Paulo           
#>  date     2019-04-08                  
#> 
#> ─ Packages ──────────────────────────────────────────────────────────────
#>  package    * version     date       lib
#>  jsonlite     1.6         2018-12-07 [1]
#>  lattice      0.20-35     2017-03-25 [1]
#>  Matrix       1.2-14      2018-04-13 [1]
#>  Rcpp         1.0.1       2019-03-17 [1]
#>  reticulate   1.10.0.9002 2019-04-08 [1]
#>  source                             
#>  CRAN (R 3.5.0)                     
#>  CRAN (R 3.5.1)                     
#>  CRAN (R 3.5.1)                     
#>  CRAN (R 3.5.2)                     
#>  Github (rstudio/reticulate@a98ff16)
#> 
#> [1] /Library/Frameworks/R.framework/Versions/3.5/Resources/library
```

<sup>Created on 2019-04-08 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

And works with the commit just before:

``` r
library(keras)
model <- keras_model_sequential() %>% layer_dense(units = 1, input_shape = 1, name = "layer1")
class(model$layers[[1]]$name)
#> [1] "character"
sessioninfo::session_info(pkgs = c("reticulate"))
#> ─ Session info ──────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.5.1 (2018-07-02)
#>  os       macOS  10.14.4              
#>  system   x86_64, darwin15.6.0        
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       America/Sao_Paulo           
#>  date     2019-04-08                  
#> 
#> ─ Packages ──────────────────────────────────────────────────────────────
#>  package    * version     date       lib
#>  jsonlite     1.6         2018-12-07 [1]
#>  lattice      0.20-35     2017-03-25 [1]
#>  Matrix       1.2-14      2018-04-13 [1]
#>  Rcpp         1.0.1       2019-03-17 [1]
#>  reticulate   1.10.0.9002 2019-04-08 [1]
#>  source                             
#>  CRAN (R 3.5.0)                     
#>  CRAN (R 3.5.1)                     
#>  CRAN (R 3.5.1)                     
#>  CRAN (R 3.5.2)                     
#>  Github (rstudio/reticulate@acb278d)
#> 
#> [1] /Library/Frameworks/R.framework/Versions/3.5/Resources/library
```

<sup>Created on 2019-04-08 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by skeydan** [comment] 2019-04-08 15:57
Hi @kevinushey could you please take a look at this whenever you have time?
@dfalbel identified the commit that causes (not frequent, but reoccurring) issues in `keras` where Python values that used to get converted to R do not any more: https://github.com/rstudio/reticulate/commit/a98ff163ac4fcb743ad4ac9eaff984069a9de258

Here is some test code (as much simplified as possible) that illustrates the issue:
(also see https://github.com/rstudio/keras/issues/732#issuecomment-480881409 for a comparison of the 2 adjacent `reticulate` states)

```
library(keras)
model <- keras_model_sequential() %>% layer_dense(units = 1, input_shape = 1, name = "layer1")

layer_name <- "layer1"

layer_dict <- model$layers

# Symptom 1
# Error: Result 1 must be a single string, not a vector of class `python.builtin.str/python.builtin.object` 
# and of length 2
names(layer_dict) <- purrr::map_chr(layer_dict , ~.x$name)
# works
names(layer_dict) <- purrr::map_chr(layer_dict , function(x) as.character(x$name))

# Symptom 2
# cannot coerce type 'environment' to vector of type 'list'
x <- layer_dict[[layer_name]]$output
# works
x <- model$get_layer(layer_name)$output 


# Symptom 2 follow-up
shape <- layer_dict[[layer_name]]$output$get_shape()
shape$as_list()
# [None, 1]

# here we get the conversion as expected
shape <- model$get_layer(layer_name)$output$get_shape()
shape$as_list()
```

Thank you!! And let us know whatever questions you have :-)

**Comment by kevinushey** [comment] 2019-04-08 18:35
Thanks -- I'll take a look!

**Comment by kevinushey** [comment] 2019-04-08 18:50
Looks like this is the commit that breaks things: https://github.com/rstudio/reticulate/commit/a98ff163ac4fcb743ad4ac9eaff984069a9de258

I'll see if I can figure out why.

**Comment by skeydan** [comment] 2019-04-08 19:01
thanks!

**Comment by skeydan** [comment] 2019-04-09 16:26
Closing as the fix was merged now (thx @kevinushey!)

**Closed by skeydan** 2019-04-09 16:26 UTC
