### ISSUE TITLE
Elementwise Product in custom layer

### ISSUE THREAD

**Issue by lysecret2** [rstudio/keras#221] opened 2017-12-18 14:17 UTC
Hey, I want to implement a "layer normalization" custom layer. However, i don't know the correct backend function to do elementwise product "*" doesnt seem to work. ( strange cause "/" does work).Here is my code. 

```

k=backend()


LayerNorm <- R6::R6Class("KerasLayer",
                                  
                                  inherit = KerasLayer,
                         
                                
                         
                                  
                                
                                  public = list(
                                    
                                    scale=NULL,
                                    shift=NULL,
                                    
                                    build = function(input_shape) {
                                     self$scale <- self$add_weight(
                                        name = 'scaleW', 
                                        shape = list(1L),
                                        initializer = initializer_random_normal(),
                                        trainable = TRUE
                                      )
                                      self$shift <- self$add_weight(
                                        name = 'shift', 
                                        shape = list(1L),
                                        initializer = initializer_constant(0),
                                        trainable = TRUE
                                      )
                                      
                                    },
                                    
                                    
                                    call = function(x, mask = NULL) {
                                      mean <- k$mean(x, axis = -1L, keepdims = TRUE)
                                      std <- k$sqrt(k$var(x,axis=-1L,keepdims=TRUE)+1e-5)
                                      
                                  
                                      normd=(x-mean)/(std+1e-5)
                                      #Here is the problem
                                      normd*self$scale+self$shift
                                      
                                    }
        
                                  )
)


# Create layer wrapper function
layer_LayerNorm <- function(object) {
  create_layer(LayerNorm, object)
}

a=c(1,2,3,1,2)
b=c(1,0,1,0,1)
inp=rbind(a,b)

i=layer_input(batch_shape =   c(2,5))
n=layer_LayerNorm(i)


```

**Comment by jjallaire** [comment] 2017-12-18 15:04
What backend are you using? For the TensorFlow back-end (the default) the `*` operator resolves to `tf.multiply` which is an element-wise multiplication: https://www.tensorflow.org/api_docs/python/tf/multiply

**Comment by lysecret2** [comment] 2017-12-18 15:11
I am using tensorflow. However, when I run the above code with the * Operator I get the error:

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  RuntimeError: Evaluation error: non-numeric argument to binary operator.

Detailed traceback: 
  File "/applvg/os/apps/Rdeps/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 602, in __call__
    output = self.call(inputs, **kwargs)
  File "/applvg/os/usr/lib64/R/library/keras/python/kerastools/layer.py", line 26, in call
    return self.r_call(inputs, mask)
  File "/applvg/os/usr/lib64/R/library/reticulate/python/rpytools/call.py", line 21, in python_function
    raise RuntimeError(res[kErrorKey])
In addition: Warning message:
In (function (x, mask = NULL)  :
  Incompatible methods ("*.tensorflow.python.ops.variables.Variable", "*.tensorflow.python.framework.ops.Tensor") for "*"

```

**Comment by jjallaire** [comment] 2017-12-18 16:39
I think that the problem is that our S3 method(s) for the `*` operator don't handle mixed types. I've just committed a change to the tensorflow package that should resolve this. Could you try installing from GitHub master to try it out:

```r
devtools::install_github("rstudio/tensorflow")
```

**Comment by lysecret2** [comment] 2017-12-18 17:42
That fixed it thanks for your help!

**Comment by lysecret2** [comment] 2017-12-20 15:28
Hey i have a follow up question. I have sequential data with multiple time steps ( 3 dimensional Inputs) And I wanted to use time_distributed to apply this layer normalization to each time step. However that gives out an error. Is there anything Special i have to look out for if I want to apply time_distributed on my custom layer?

**Comment by jjallaire** [comment] 2017-12-20 15:42
Nothing special that I am aware of

**Comment by lysecret2** [comment] 2017-12-20 20:29
OK. If I time distribute a layer, what are the input dimension on the layer I time distribute on? Say May Input is 10 3 2, ( so 3 time steps) If i time distribute my layer is the dimension of the input then 10 2 ?

**Comment by lysecret2** [comment] 2017-12-21 16:22
So the custom layer owrks now, but if i try to "tim_distribute" it i get an error:

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: can only concatenate tuple (not "list") to tuple

Detailed traceback: 
  File "/applvg/os/apps/Rdeps/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 621, in __call__
    output_shape = self.compute_output_shape(input_shape)
  File "/applvg/os/apps/Rdeps/anaconda3/lib/python3.6/site-packages/keras/layers/wrappers.py", line 166, in compute_output_shape
    return (child_output_shape[0], timesteps) + child_output_shape[1:]
```

you can reproduce it by running the following code: 
```

k=backend()


LayerNorm <- R6::R6Class("KerasLayer",
                         
                         inherit = KerasLayer,
                         
                         
                         
                         
                         
                         public = list(
                           
                           scale=NULL,
                           shift=NULL,
                           
                           build = function(input_shape) {
                             self$scale <- self$add_weight(
                               name = 'scaleW', 
                               shape = list(1L),
                               initializer = initializer_random_normal(),
                               trainable = TRUE
                             )
                             self$shift <- self$add_weight(
                               name = 'shift', 
                               shape = list(1L),
                               initializer = initializer_constant(0),
                               trainable = TRUE
                             )
                             
                           },
                           
                           
                           call = function(x, mask = NULL) {
                             mean <- k$mean(x, axis = -1L, keepdims = TRUE)
                             std <- k$sqrt(k$var(x,axis=-1L,keepdims=TRUE)+1e-5)
                             
                             
                             normd=(x-mean)/(std+1e-5)
                             #Here is the problem
                             normd*self$scale+self$shift
                             
                           }
                           
                         )
)


# Create layer wrapper function
layer_LayerNorm <- function(object) {
  create_layer(LayerNorm, object)
}


i=layer_input(batch_shape =   c(2,3,5))
n=time_distributed(i,layer_LayerNorm())


```

**Closed** 2018-09-11 19:56 UTC
